python3  main_3op_enhance_39.py \
    --model_path /data/chx/FLUX.1-dev_RF-Solver     \
    --eval-datasets EditEval_v1     \
    --height 1024     \
    --width 1024     \
    --num-step 30     \
    --guidance_scale 3.5     \
    --inject 8     \
    --use_inversed_latents     \
    --nudge 1.05     \
    --ilist_json_path ./ilist_data_EditEval_v1.json     \
    --output_dir ./outputs/3op_enhance_EditEval_v1_new_test39     \
    --test     \
    --enhanced     \
    --stable_flow